#!/usr/bin/env python
"""Auto-generate LaTeX tables for Paper 1 from training-run summaries.

Closes P0.5 in ``docs/paper/GAPS_AND_PLAN.md``. The appendix table is
generated by walking ``data/runs/`` and reading every
``summary.json``; the headline ablation table is generated from a
hand-curated subset. Both write into
``docs/paper/paper_1_kanto/tables/``.

Single source of truth: the per-run ``summary.json`` files. Updating
the prose number means re-running this script.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

LOG = logging.getLogger("scripts.build_paper_tables")


# ---------------------------------------------------------------------------
# Hand-curated row order for the headline ablation table (Table~\ref{tab:ablation}).
# Each entry: (run_dir name, display label, group letter for visual grouping).
# Edit this list before re-running.
# ---------------------------------------------------------------------------
ABLATION_CELLS = [
    ("kanto_full_4k_30ep",                       "matern52 + const + 4k", "S"),  # scale baseline
    ("kanto_full_6k_50ep_cuda",                  "matern52 + const + 6k (50ep)", "S"),
    ("kanto_full_6k_50ep_matern32",              "matern32 + const + 6k", "K"),
    ("kanto_full_6k_50ep_matern12",              "matern12 + const + 6k", "K"),
    ("kanto_full_6k_50ep_rbf",                   "rbf + const + 6k", "K"),
    ("kanto_full_6k_50ep_linear_mean_v2",        "matern52 + linear + 6k", "M"),
    ("kanto_full_6k_50ep_kmeans_pp_stratified",  "matern52 + const + 6k (k-means strat)", "I"),
    ("kanto_full_8k_50ep_matern52_8k",           "matern52 + const + 8k", "I"),
    ("kanto_full_6k_50ep_best_of_combo",         "rbf + linear + 6k (k-means strat)", "X"),
    ("kanto_full_6k_50ep_studentt",              "Student-t (df=4) + linear + 6k", "L"),
    ("kanto_full_6k_50ep_studentt_constant",     "Student-t (df=4) + const + 6k", "L"),
    ("kanto_full_6k_50ep_studentt_linear_df8",   "Student-t (df=8) + linear + 6k", "L"),
    ("kanto_full_8k_50ep_linear_8k",             "matern52 + linear + 8k", "M"),
    ("kanto_full_6k_50ep_linear_rbf",            "rbf + linear + 6k (\\textbf{ours})", "B"),
    ("kanto_full_6k_50ep_linear_rbf_enc48",      "rbf + linear + 6k + 48-D encoder", "C"),
    ("kanto_full_8k_50ep_linear_rbf_8k",         "rbf + linear + 8k", "C"),
]

GROUP_LEGEND = {
    "S": "scaling",
    "K": "kernel sweep",
    "M": "mean sweep",
    "I": "inducing sweep",
    "L": "likelihood (Student-t null)",
    "X": "best-of-combo (counter-example)",
    "B": "\\textbf{best}",
    "C": "capacity saturation probes",
}


def _read_summary(path: Path) -> dict | None:
    if not path.exists():
        LOG.warning("missing %s", path)
        return None
    return json.loads(path.read_text())


def _fold_mean(folds: list[dict], key: str) -> float:
    return sum(f[key] for f in folds) / len(folds)


def build_appendix_table(runs_dir: Path) -> str:
    """One row per cell in :data:`ABLATION_CELLS`."""
    rows = []
    for slug, label, group in ABLATION_CELLS:
        summary = _read_summary(runs_dir / slug / "summary.json")
        if summary is None:
            rows.append(f"  {label} & --- & --- & --- & --- \\\\")
            continue
        folds = summary["spatial_kfold"]
        rmse = _fold_mean(folds, "rmse")
        mae = _fold_mean(folds, "mae")
        loss = summary.get("final_loss", float("nan"))
        n_ind = summary.get("n_inducing", "—")
        rows.append(
            f"  {label} & {n_ind} & {loss:.4f} & {rmse:.3f} & {mae:.3f} \\\\"
        )

    legend = "\\quad ".join(f"\\textit{{{k}: {v}}}" for k, v in GROUP_LEGEND.items())
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/build_paper_tables.py. DO NOT EDIT BY HAND.
\\begin{{table}}[ht]
  \\caption{{Full ablation summary. \\textbf{{Training-fit
            diagnostic only; not held-out proper $K$-fold}}
            (see Section~\\ref{{sec:results:ablation_note}}).
            All cells share the same spatial 3-fold (mesh-L2,
            seed 42) train-on-all + per-fold-report protocol on
            \\KantoNRows{{}} rows. Loss is the final ELBO (Gaussian
            cells) or Student-t equivalent (heavy-tail cells; not
            directly comparable to Gaussian rows).}}
  \\label{{tab:ablation_full}}
  \\centering
  \\small
  \\begin{{tabular}}{{l r r r r}}
    \\toprule
    Configuration & $M$ & Final loss & RMSE & MAE \\\\
    \\midrule
{body}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""


def main(argv: list[str] | None = None) -> int:
    repo = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs-dir", type=Path, default=repo / "data/runs")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=repo / "docs/paper/paper_1_kanto/tables",
    )
    parser.add_argument("--log-level", default="INFO")
    args = parser.parse_args(argv)
    logging.basicConfig(level=args.log_level, format="%(asctime)s %(levelname)s %(message)s")
    args.out_dir.mkdir(parents=True, exist_ok=True)

    appendix = build_appendix_table(args.runs_dir)
    out = args.out_dir / "ablation_full.tex"
    out.write_text(appendix)
    LOG.info("Wrote %s", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
